### ISSUE TITLE
Make webots start up automatically when "WPILib: Simulate Robot Code on Desktop" task is run.

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/RobotCodeSimulator#11]

**Comment by brettle** [comment]
Not clear this is actually desirable. You don't want multiple copies of webots running if you run the task multiple times. At times, you might also want to just use the wpilib simulator without webots. Some people might not have webots installed, for example. Imo, it's not a big deal to start webots once when you're developing.
