### ISSUE TITLE
MockSparkMax should be rewritten to be compatible with Mac

### ISSUE THREAD

**Issue by alexander-mcdowell** [DeepBlueRobotics/RobotCodeSimulator#9]
Currently, if you were to run the master branch on Mac, it would throw an error because SparkMaxDriver.dll is not included in the project. One way to fix this (while we wait for third-party vendors such as CTRE and Rev Robotics) is by stubbing every method that a CANSparkMax has and only writing the methods we use most frequently. You can see an example of what I mean in MockPhoenixController.java.

**Comment by brettle** [comment]
Have you checked whether the ctre libs available on the beta site fix this?

**Comment by CoolSpy3** [comment]
> Have you checked whether the ctre libs available on the beta site fix this?

The ctre libs just point to ctre's website. They don't provide a custom installer which would install RevRobotics libs
